spring:
  datasource:
    url: jdbc:mariadb://10.11.10.29:3306/helloakka?serverTimezone=Asia/Seoul&autoReconnect=true
    username: root
    password: VMware1!
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: hello-akka
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
